/**
 * 공동체 — 한 교회/모임의 울타리.
 *
 * 묵상·감사·통독은 전부 공동체 안에서만 오간다.
 * 다른 공동체의 글은 화면에서 가리는 게 아니라 **서버가 아예 내보내지 않는다.**
 */
export interface Community {
  /** 겉으로 드러나는 짧은 이름표. 짐작할 수 없게 무작위로 만든다 */
  id: string;
  /** "○○교회 청년부" 처럼 사람에게 보이는 이름 */
  name: string;
  /** 새 지체를 들일 때 알려주는 6자리. 새어나가면 관리자가 다시 발급한다 */
  joinCode: string;
  /** 이 공동체를 만든 사람 (첫 관리자) */
  createdBy: string;
  createdAt: string;
  /** 꺼두면 아무도 못 들어온다 (앱 운영자만 조작) */
  active: boolean;
}

export interface User {
  id: string;
  name: string;
  role: 'admin' | 'member';
  pin: string; // 4-digit PIN code
  createdAt: string;
  /**
   * 어느 공동체 사람인지.
   * ⚠️ 이 값은 **요청에 실려 온 것을 믿지 않는다.** 로그인 증표 안에 든 것만 쓴다.
   * 그러지 않으면 남의 공동체 이름을 적어 보내 묵상을 들여다볼 수 있다.
   */
  communityId?: string;
  /** 앱 전체 운영자. 공동체 목록·정지만 가능하고 남의 공동체 글은 못 본다 */
  isAppOwner?: boolean;
}

export interface Notice {
  id: string;
  date: string; // YYYY-MM-DD
  verseTitle: string; // e.g. "창세기 1:1"
  verseText: string; // Bible text
  content: string; // Additional commentary or announcement from admin
  createdBy: string; // admin user name
  readBy: string[]; // List of user IDs who clicked read
}

export interface Comment {
  id: string;
  userId: string;
  userName: string;
  content: string;
  createdAt: string;
}

export interface SokGroup {
  id: string;
  name: string; // e.g. "1속", "청년1속", "사랑속"
  description?: string;
  memberUserIds: string[]; // List of user IDs assigned to this sok
  createdAt: string;
}

/** 글에 남길 수 있는 반응. 글쓰기가 부담스러운 분도 누를 수 있는 최저 문턱. */
export type ReactionType = "like" | "pray";

/** 반응 종류별로 누른 사람 ID 목록 */
export type Reactions = Partial<Record<ReactionType, string[]>>;

export interface Meditation {
  id: string;
  userId: string;
  userName: string;
  date: string; // YYYY-MM-DD
  verseTitle: string; // Which verse this meditation is about
  title: string;
  /** 골라 온 성경 구절 + 내 묵상이 한 덩어리로 들어간다 (보여줄 때 앞머리 구절만 굵게) */
  content: string;
  prayer: string; // Prayer topic/response
  likes: string[]; // (구버전 호환) 기존 '좋아요'. 신규 UI 는 reactions 를 쓴다.
  /** 반응. 'pray' 개수는 기도제목 아래 "N명이 당신을 위해 기도했습니다" 로도 보여준다. */
  reactions?: Reactions;
  comments: Comment[];
  createdAt: string;
  sokId?: string | null; // Optional ID of the sok (null/undefined if public/all)
}

export interface WeeklySummary {
  id: string;
  weekLabel: string; // e.g., "7월 3주차 요약"
  summaryText: string; // Markdown summary generated by AI
  generatedAt: string;
}

export interface AlarmConfig {
  id: string;
  userId: string;
  time: string; // "HH:MM"
  enabled: boolean;
  days: number[]; // [0, 1, 2, 3, 4, 5, 6] (0 = Sunday, etc)
  /**
   * 이 알림을 마지막으로 보낸 한국 날짜 ("YYYY-MM-DD").
   * 서버가 다시 켜져도 같은 날 두 번 울리지 않게 하는 표시다.
   */
  lastFiredDate?: string;
}

export interface BiblePlan {
  book: string; // e.g., "요한복음"
  currentChapter: number;
  active: boolean;
  lastUpdatedDate?: string; // YYYY-MM-DD
  /**
   * 이 진도를 마지막으로 고친 시각(ISO).
   * 원격과 합칠 때 어느 쪽이 최신인지 가리는 기준이다.
   * 이게 없으면 원격의 옛 진도가 방금 넘긴 장을 덮어써서 같은 장이 반복된다.
   */
  updatedAt?: string;
}

export interface UserBibleProgress {
  userId: string;
  goalTitle: string; // e.g. "1년 1독 (매일 3장)"
  targetChapters: number; // e.g. 1189 for full Bible
  dailyTarget: number; // e.g. 3
  lastReadBook: string; // e.g. "요한복음"
  lastReadChapter: number; // e.g. 1
  completedChapters: string[]; // e.g. ["창세기 1", "요한복음 1"]
  updatedAt: string;
}

export interface GratitudeNote {
  id: string;
  userId: string;
  userName: string;
  isAnonymous: boolean;
  date: string; // YYYY-MM-DD
  content: string;
  likes: string[];
  reactions?: Reactions;
  comments: Comment[];
  createdAt: string;
}

export interface BibleQA {
  id: string;
  question: string;
  answer: string;
  category?: string; // e.g. "성경 역사 & 배경", "신학 질문", "성경 구절 이해"
  likes: string[];
  comments: Comment[];
  createdAt: string;
}

/** 한 기기(브라우저)의 푸시 구독 정보. 사람 한 명이 폰·PC 등 여러 개를 가질 수 있다. */
export interface PushSubscriptionRecord {
  userId: string;
  endpoint: string;
  keys: { p256dh: string; auth: string };
  userAgent?: string;
  createdAt: string;
}

/** 푸시 발신자 신원(VAPID). 한 번 만들면 바뀌면 안 된다 — 바뀌면 기존 구독이 전부 무효가 됨. */
export interface VapidKeys {
  publicKey: string;
  privateKey: string;
}

/**
 * 나눔 목표. 주 단위로 정하고, 화면에서는 이번 달 진행률로 보여준다.
 * (이번 달 목표 = 주간 목표 x 4주)
 */
export interface SharingGoal {
  userId: string;
  weeklyMeditations: number;  // 한 주에 묵상 몇 회
  weeklyGratitudes: number;   // 한 주에 감사·칭찬 몇 회
  updatedAt: string;
}

/** 성경을 읽다 눌러서 체크해 둔 구절. 나의기록 > 말씀 체크리스트에서 모아 본다. */
export interface SavedVerse {
  id: string;
  userId: string;
  book: string;        // "요한복음"
  chapter: number;     // 3
  verseNum: number;    // 16
  text: string;        // 본문
  createdAt: string;
}

/**
 * 성경읽기 챌린지.
 *
 * 관리자가 성경 한 권과 목표일을 정하고 참가자를 고르면 탭이 하나 생긴다.
 * 진행률은 따로 세지 않고 **성경통독의 '읽음' 표시를 그대로 읽는다** —
 * 통독에서 완료를 누르면 챌린지 진행률에도 바로 반영된다.
 *
 * 챌린지가 도는 동안 감사·칭찬 탭은 잠시 접어 둔다 (탭이 너무 많아지지 않게).
 * 끝나면 그 다음 날 감사 탭이 돌아온다.
 */
export interface ReadingChallenge {
  id: string;
  /** "마가복음 함께 읽기" 처럼 화면에 보이는 이름 */
  title: string;
  /** 읽을 성경 한 권 (예: "마가복음") */
  book: string;
  /** 그 권의 총 장 수 */
  totalChapters: number;
  startDate: string; // YYYY-MM-DD (한국 날짜)
  endDate: string;   // YYYY-MM-DD 목표일
  /** 참가자. 중간에 더 넣을 수 있다 */
  participantIds: string[];
  createdBy: string;
  createdAt: string;
  status: "active" | "done";
  /**
   * 끝난 날(한국 날짜). 이 날까지는 챌린지 탭이 남아 축하를 보여주고,
   * **다음 날부터** 감사 탭이 돌아온다.
   */
  completedDate?: string;
}

/**
 * 개인 영성일기 — **오직 쓴 사람만 봅니다.**
 *
 * 묵상나눔과 달리 공동체에 공유되지 않습니다. 목록을 부르는 API 도
 * 로그인 증표에 적힌 본인 것만 돌려주고, 남의 것은 서버가 아예 내보내지 않습니다.
 * 성령님이 주시는 마음·느낌·꿈처럼 남에게 말하기 어려운 것을 쌓아 두는 자리입니다.
 */
export interface JournalEntry {
  id: string;
  /** 주인. 이 값과 다른 사람에게는 절대 보이지 않는다 */
  userId: string;
  date: string; // YYYY-MM-DD
  /** 함께 붙잡은 말씀 (선택) */
  verseTitle: string;
  title: string;
  content: string;
  /** 기도제목 (선택) */
  prayer: string;
  createdAt: string;
  updatedAt?: string;
}

/**
 * 한 공동체가 담고 있는 것 전부.
 *
 * 이름이 Database 로 시작하지만 실제로는 **공동체 하나치**다.
 * (앱이 하나의 공동체로만 돌던 시절의 이름을 그대로 두었다 —
 *  서버 코드 200 곳 가까이가 이 이름을 쓰고 있어 바꾸면 얻는 것보다 잃는 게 크다)
 */
export interface DatabaseSchema {
  users: User[];
  notices: Notice[];
  meditations: Meditation[];
  sokGroups?: SokGroup[];
  gratitudes?: GratitudeNote[];
  bibleQAs?: BibleQA[];
  summaries: WeeklySummary[];
  alarmConfigs: AlarmConfig[];
  biblePlan?: BiblePlan;
  userBibleProgress?: Record<string, UserBibleProgress>;
  sharingGoals?: Record<string, SharingGoal>;
  savedVerses?: SavedVerse[];
  /** 성경읽기 챌린지. 도는 것은 한 번에 하나로 둔다 */
  challenges?: ReadingChallenge[];
  /** 개인 영성일기. 본인 외에는 절대 내보내지 않는다 */
  journals?: JournalEntry[];
  pushSubscriptions?: PushSubscriptionRecord[];
  vapidKeys?: VapidKeys;
  /** 로그인 증표에 서명하는 비밀키. 이게 바뀌면 모두 다시 로그인해야 한다 */
  sessionSecret?: string;
  /**
   * 비밀번호 재설정을 이미 적용했다는 표시.
   * 콘솔의 환경변수를 지우지 않고 두더라도, 서버가 다시 뜰 때마다
   * 비밀번호가 옛 값으로 되돌아가는 일을 막는다.
   */
  pinResetMark?: string;
  updatedAt?: string;
}

