export interface User {
  id: string;
  name: string;
  role: 'admin' | 'member';
  pin: string; // 4-digit PIN code
  createdAt: string;
}

export interface Notice {
  id: string;
  date: string; // YYYY-MM-DD
  verseTitle: string; // e.g. "창세기 1:1"
  verseText: string; // Bible text
  content: string; // Additional commentary or announcement from admin
  createdBy: string; // admin user name
  readBy: string[]; // List of user IDs who clicked read
}

export interface Comment {
  id: string;
  userId: string;
  userName: string;
  content: string;
  createdAt: string;
}

export interface SokGroup {
  id: string;
  name: string; // e.g. "1속", "청년1속", "사랑속"
  description?: string;
  memberUserIds: string[]; // List of user IDs assigned to this sok
  createdAt: string;
}

export interface Meditation {
  id: string;
  userId: string;
  userName: string;
  date: string; // YYYY-MM-DD
  verseTitle: string; // Which verse this meditation is about
  title: string;
  content: string;
  prayer: string; // Prayer topic/response
  likes: string[]; // List of user IDs who liked this
  comments: Comment[];
  createdAt: string;
  sokId?: string | null; // Optional ID of the sok (null/undefined if public/all)
}

export interface WeeklySummary {
  id: string;
  weekLabel: string; // e.g., "7월 3주차 요약"
  summaryText: string; // Markdown summary generated by AI
  generatedAt: string;
}

export interface AlarmConfig {
  id: string;
  userId: string;
  time: string; // "HH:MM"
  enabled: boolean;
  days: number[]; // [0, 1, 2, 3, 4, 5, 6] (0 = Sunday, etc)
}

export interface BiblePlan {
  book: string; // e.g., "요한복음"
  currentChapter: number;
  active: boolean;
  lastUpdatedDate?: string; // YYYY-MM-DD
}

export interface UserBibleProgress {
  userId: string;
  goalTitle: string; // e.g. "1년 1독 (매일 3장)"
  targetChapters: number; // e.g. 1189 for full Bible
  dailyTarget: number; // e.g. 3
  lastReadBook: string; // e.g. "요한복음"
  lastReadChapter: number; // e.g. 1
  completedChapters: string[]; // e.g. ["창세기 1", "요한복음 1"]
  updatedAt: string;
}

export interface GratitudeNote {
  id: string;
  userId: string;
  userName: string;
  isAnonymous: boolean;
  date: string; // YYYY-MM-DD
  content: string;
  likes: string[];
  comments: Comment[];
  createdAt: string;
}

export interface BibleQA {
  id: string;
  question: string;
  answer: string;
  category?: string; // e.g. "성경 역사 & 배경", "신학 질문", "성경 구절 이해"
  likes: string[];
  comments: Comment[];
  createdAt: string;
}

export interface DatabaseSchema {
  users: User[];
  notices: Notice[];
  meditations: Meditation[];
  sokGroups?: SokGroup[];
  gratitudes?: GratitudeNote[];
  bibleQAs?: BibleQA[];
  summaries: WeeklySummary[];
  alarmConfigs: AlarmConfig[];
  biblePlan?: BiblePlan;
  userBibleProgress?: Record<string, UserBibleProgress>;
  updatedAt?: string;
}

